apiVersion: v1
kind: Pod
metadata:
    name: static-site-pod
    labels:
        app: static-site
spec:
    containers:
        - name: static-site-container
          image: hub.docker.com/static-site:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 5000 
